version: "3"
services:
  nginx:
    image: ghcr.io/kduma-utilities-stats/server/nginx:v2
    restart: always
    expose:
      - 80
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - internal

  php:
    image: ghcr.io/kduma-utilities-stats/server/fpm:v2
    restart: always
    networks:
      - internal
    depends_on:
      - db
    volumes:
      - jobs_data:/var/www/html/storage/app/jobs
      - cache_data:/var/www/html/storage/framework/cache/data
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=utilities_stats_server
      - DB_USERNAME=utilities_stats_server
      - DB_PASSWORD=${DB_PASSWORD}

      - APP_DEBUG=true
      - LOG_LEVEL=errorlog
      - APP_KEY=${APP_KEY}

  cron:
    image: ghcr.io/kduma-utilities-stats/server/cron:v2
    restart: always
    networks:
      - internal
    depends_on:
      - db
    volumes:
      - jobs_data:/var/www/html/storage/app/jobs
      - cache_data:/var/www/html/storage/framework/cache/data
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=utilities_stats_server
      - DB_USERNAME=utilities_stats_server
      - DB_PASSWORD=${DB_PASSWORD}

      - APP_DEBUG=true
      - LOG_LEVEL=errorlog
      - APP_KEY=${APP_KEY}

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=utilities_stats_server
      - MYSQL_USER=utilities_stats_server
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - internal
    volumes:
      - db_data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  db_data: {}
  jobs_data: {}
  cache_data: {}
